/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Indian.State.Census.Analyzer;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
